Repository jjaniec/42sh, pull requests merged in 2018-08, with the labels that each got.

#13 Makefile: fix linking order for linux
  Makefile
  srcs/exec/exec.c
Labels: ┬─┬ノ( ͡° ͜ʖ ͡°ノ)

#14 Makefile tests nonverbose
  .codacy.yml
  .travis.yml
  Makefile
  tests/ast_tree/7.txt
  tests/main.c
Labels: Bug Fix, enhancement

#15 Subprompt
  Makefile
  includes/ast.h
  includes/twenty_one_sh.h
  srcs/ast/ast.c
  srcs/ast/ast_construct.c
  srcs/ast/ast_debug.c
  srcs/ast/check_parsing.c
  srcs/ast/prepare_argv.c
  srcs/exec/exec.c
  srcs/exec/manage_path.c
  srcs/lexer/lexeme_type_word.c
  srcs/lexer/lexer.c
  srcs/line_edition/line_edition.c
  srcs/main.c
  srcs/sub_prompt.c
  tests/ast_tests.c
  tests/ast_tree/1.txt
  tests/ast_tree/2.txt
  tests/ast_tree/3.txt
  tests/ast_tree/4.txt
  tests/ast_tree/5.txt
  tests/ast_tree/6.txt
  tests/ast_tree/7.txt
  tests/ast_tree/8.txt
  tests/exec_tests.c
  tests/lexer_tests.c
Labels: Bug Fix, enhancement

#19 Syntax highlighting
  .travis.yml
  Makefile
  includes/syntax_highlighting.h
  includes/twenty_one_sh.h
  srcs/exec/exec.c
  srcs/exec/manage_path.c
  srcs/main.c
  srcs/syntax_highlighting/print_colorized_input.c
  srcs/syntax_highlighting/print_lexeme_colorized.c
  tests/main.c
  tests/syntax_highlighting_tests.c
  tests/tests.h
Labels: enhancement
